name: GitHub Actions Demo
env:
   AARCH64: arm64
   X86_64: amd64
   env_file: .env

on:
  schedule:
    - cron: '30 5,17 * * * *'
  push:
    tags:
      - '*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: export RELEASE_VERSION=$(curl --silent "https://api.github.com/repos/tailscale/tailscale/tags" | jq -r '.[0].name'); echo "RELEASE_VERSION=$RELEASE_VERSION" >> $env_file

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "RELEASE_VERSION"
          replace: ${{env.RELEASE_VERSION}}
          include: "apk/CONTROL/config.json"
          regex: false

      - run: ARCH=${X86_64} ./scripts/build.sh
      - run: sudo ./scripts/apkg-tools_py3.py create apk

      - run: ARCH=${AARCH64} ./scripts/build.sh
      - run: sudo ./scripts/apkg-tools_py3.py create apk

      - uses: actions/upload-artifact@v2
        with:
          name: tailscale_${{env.RELEASE_VERSION}}_${ARCH}.apk
          path: tailscale_${{env.RELEASE_VERSION}}_${ARCH}.apk
