name: GitHub Actions Auto Builder
env:
   AARCH64: arm64
   X86_64: amd64
   env_file: .env

on:
  push:
  schedule:
    - cron: '0 6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Builder
        run: export RELEASE_VERSION=$(curl --silent "https://api.github.com/repos/tailscale/tailscale/tags" | jq -r '.[0].name'); echo "export RELEASE_VERSION=$RELEASE_VERSION" >> $env_file

      - run: source $env_file; sed -i "|RELEASE_VERSION|$RELEASE_VERSION|" apk/CONTROL/config.json

      - run: ARCH=${X86_64} ./scripts/build.sh
      - run: sudo ./scripts/apkg-tools_py3.py create apk

      - run: ARCH=${AARCH64} ./scripts/build.sh
      - run: sudo ./scripts/apkg-tools_py3.py create apk

      - uses: actions/upload-artifact@v2
        with:
          name: tailscale_${{env.RELEASE_VERSION}}_${ARCH}.apk
          path: tailscale_${{env.RELEASE_VERSION}}_${ARCH}.apk
