name: GitHub Actions Demo
on:
  push:
    tags:
      - '*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "RELEASE_VERSION"
          replace: ${{env.RELEASE_VERSION}}
          include: "apk/CONTROL/config.json"
          regex: false

      - run: ./scripts/build.sh
      - run: sudo ./scripts/apkg-tools_py3.py create apk

      - uses: actions/upload-artifact@v2
        with:
          name: tailscale_${{env.RELEASE_VERSION}}_x86-64.apk
          path: tailscale_${{env.RELEASE_VERSION}}_x86-64.apk
